# permissions for end users to view tektonpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tektonpipeline-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tektonpipeline
    app.kubernetes.io/part-of: tektonpipeline
    app.kubernetes.io/managed-by: kustomize
  name: tektonpipeline-viewer-role
rules:
- apiGroups:
  - tekton.nttdata.com
  resources:
  - tektonpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.nttdata.com
  resources:
  - tektonpipelines/status
  verbs:
  - get
